---
contentdir: "content"
layoutdir: "layouts"
publishdir: "public"
baseurl: "https://zubieta.github.io/z10z"
title: "Z10Z"
disqusShortname: "Z10Z721"
permalinks:
  post: "/:year/:month/:slug/"
theme: "twentyfourteen"
taxonomies:
  tag: "tags"
  category: "categories"
  series: "series"
params:
  AuthorName: "Santiago Martin Zubieta Ortiz"
  Description: "Loves Beer, Science, Computers, You."
  Copyright: "Copyright (c) 2015, Santiago Zubieta; some rights reserved."
  GitHubUser: "zubieta"
  CVURL: "https://drive.google.com/file/d/0B12b-KIslM3hR3VVTFlXeERRRVE/view"
---