---
contentdir: "content/post"
layoutdir: "layouts"
publishdir: "public"
baseurl: "https://zubie7a.github.io/z10z"
title: "Z10Z"
permalinks:
  post: "/:year/:month/:slug/"
theme: "twentyfourteen"
taxonomies:
  tag: "tags"
  category: "categories"
  series: "series"
params:
  AuthorName: "Santiago Martin Zubieta-Ortiz"
  Description: "Astronomer in dreams, Computer Scientist wannabe, Digital Art amateur."
  Copyright: "Copyright (c) 2020, Santiago Zubieta; some rights reserved."
  GitHubUser: "zubie7a"
  CVURL: "https://drive.google.com/open?id=18lOJgr3RF1NUz89Tr5SKewX9X0lJTBab"
  disqusShortname: "z10z"
---
