---
contentdir: "content"
layoutdir: "layouts"
publishdir: "public"
baseurl: "https://zubieta.github.io/z10z"
title: "Z10Z"
permalinks:
  post: "/:year/:month/:slug/"
theme: "twentyfourteen"
taxonomies:
  tag: "tags"
  category: "categories"
  series: "series"
params:
  AuthorName: "Santiago Martin Zubieta Ortiz"
  Description: "Loves Beer, Science, Computers, You."
  Copyright: "Copyright (c) 2015, Santiago Zubieta; some rights reserved."
  GitHubUser: "zubieta"
  CVURL: "https://github.com/Zubieta/z10z/raw/master/cv/cv.pdf"
---